# Generated by Django 4.1.2 on 2022-10-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attendance_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
