# Generated by Django 4.1.3 on 2022-12-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_student_attendance_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="block_hours",
            field=models.IntegerField(default=1),
        ),
    ]
