# Generated by Django 4.1.3 on 2022-12-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_course_block_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessions",
            name="block_hours",
            field=models.IntegerField(default=1),
        ),
    ]
